### ISSUE TITLE
MissingMethod exception after updating SwaggerGen to 6.3.0

### ISSUE THREAD

**Issue by CaringDev** [Dorin-Mocan/SignalRSwaggerGen#18]
Swashbuckle.SwaggerGen introduced a binary breaking change from 6.2.x to 6.3.0 by adding a new `routeInfo` (default) parameter to [ISchemaGenerator.GenerateSchema](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/compare/v6.2.3...v6.3.0#diff-c46727841a546aa50b440ab58346c751cc554e3dcc0383df7da7920523e641b6). This leads to:
> System.MissingMethodException: Method not found: 'Microsoft.OpenApi.Models.OpenApiSchema Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator.GenerateSchema(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, System.Reflection.MemberInfo, System.Reflection.ParameterInfo)'.
   at SignalRSwaggerGen.SignalRSwaggerGen.GetOpenApiSchema(DocumentFilterContext context, Type type)
   at SignalRSwaggerGen.SignalRSwaggerGen.<>c__DisplayClass8_0.<ToOpenApiParameters>b__0(ParameterInfo param)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SignalRSwaggerGen.SignalRSwaggerGen.AddOpenApiPath(OpenApiDocument swaggerDoc, DocumentFilterContext context, SignalRHubAttribute hubAttribute, String tag, String methodPath, Operation operation, String summary, String description, IEnumerable`1 methodParams, ParameterInfo methodReturnParam, MethodInfo method, MemberElement methodXml)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessMethod(OpenApiDocument swaggerDoc, DocumentFilterContext context, SignalRHubAttribute hubAttribute, String hubPath, String tag, MethodInfo method, MemberElement methodXml)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessHub(OpenApiDocument swaggerDoc, DocumentFilterContext context, Type hub, XmlComments xmlComments)
   at SignalRSwaggerGen.SignalRSwaggerGen.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Strictly, this is a problem of SwaggerGen, however... Would you consider bumping SwaggerGen to the latest version?

**Comment by Dorin-Mocan** [comment]
@CaringDev , of course! I'll release a new version asap. Stay tuned. Thanks for letting me know about the issue.

**Comment by Dorin-Mocan** [comment]
@CaringDev , version 3.1.0 released. Please check.

**Comment by CaringDev** [comment]
Thanks, 3.1.0 works like a charm.
