### ISSUE TITLE
2 different parameter types with same type exception

### ISSUE THREAD

**Issue by AlanMacdonald** [Dorin-Mocan/SignalRSwaggerGen#4]
Hello,

I am not sure if this is a defect in SignalRSwaggerGen or Swagger, but if you have 2 different hub methods, taking 2 different input types with the same type names, but different namespaces then it throws an exception because it thinks the schema already exists

In this particular case I had this because you can update a document's permissions via one call and update details about the document directly via a different call and so they both have input types called UpdateDocumentDto but in different fully qualified namespaces so it compiles and runs fine but throws on swagger UI page.

An unhandled exception has occurred while executing the request.

Exception: 
System.InvalidOperationException: Can't use schemaId "$UpdateDocumentDto" for type "$Services.Standard.Documents.Permissions.InputDtos.UpdateDocumentDto". The same schemaId is already used for type "$Services.Standard.Documents.InputDtos.UpdateDocumentDto"
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.RegisterType(Type type, String schemaId)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateReferencedSchema(DataContract dataContract, SchemaRepository schemaRepository, Func`1 definitionFactory)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateConcreteSchema(DataContract dataContract, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForType(Type modelType, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchema(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at SignalRSwaggerGen.SignalRSwaggerGen.GetOpenApiSchema(DocumentFilterContext context, Type type)
   at SignalRSwaggerGen.SignalRSwaggerGen.<>c__DisplayClass8_0.<ToOpenApiParameters>b__0(ParameterInfo arg)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SignalRSwaggerGen.SignalRSwaggerGen.AddOpenApiPath(OpenApiDocument swaggerDoc, DocumentFilterContext context, String tag, String methodPath, OperationType operationType, String summary, String description, IEnumerable`1 methodArgs, ParameterInfo methodReturnArg)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessMethod(OpenApiDocument swaggerDoc, DocumentFilterContext context, SignalRHubAttribute hubAttribute, String hubPath, String tag, MethodInfo method)
   at SignalRSwaggerGen.SignalRSwaggerGen.ProcessHub(OpenApiDocument swaggerDoc, DocumentFilterContext context, Type hub)
   at SignalRSwaggerGen.SignalRSwaggerGen.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Dorin-Mocan** [comment]
@AlanMacdonald , i'll check right away and come back with a response. Stay tuned.

**Comment by AlanMacdonald** [comment]
Don't worry about rushing. I renamed one of the types involved so it's not a pressing issue. Thanks!

**Comment by Dorin-Mocan** [comment]
@AlanMacdonald , the problem is with how Swagger generator registers the schemas for types. It basically stores the schemas in a dictionary in which the keys are the type names(without namespace). You'll encounter the same problem if you try use in the same controller two models with same type name, but different namespace. So, unfortunately the problem is not in SignalRSwaggerGen, so I can't fix it. I can't even use a workaround where I could generate a custom key and pass it to the swagger method that generates the schema, because swagger only provides one method for generating the schema and that method expects a type as a parameter. Sorry :|

**Comment by AlanMacdonald** [comment]
Thanks for looking into that and confirming the issue is in Swagger.
